[tool.poetry]
name = "corona"
version = "0.1.0"
description = ""
authors = ["sensei4 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
web3 = "^5.23.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
